apiVersion: v2
name: cubestore
description: A Helm chart for Cubestore
type: application
version: 0.4.0
appVersion: "0.31.47"
keywords:
  - cube
  - cubejs
  - cubestore
maintainers:
  - email: luc.vauvillier@gmail.com
    name: Luc Vauvillier
sources:
  - https://github.com/gadsme/charts
  - https://github.com/cube-js/cube.js
